[colors.bright]
black = "#f9f8fe"
blue = "#ff716a"
cyan = "#5cc6d1"
green = "#5cc6d1"
magenta = "#cb75f7"
red = "#fd2e59"
white = "#23252e"
yellow = "#ffc46b"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#23252e"
blue = "#ff716a"
cyan = "#5cc6d1"
green = "#5cc6d1"
magenta = "#cb75f7"
red = "#fd2e59"
white = "#f9f8fe"
yellow = "#ffc46b"

[colors.primary]
background = "#23252e"
foreground = "#f9f8fe"

[font]
size = 13.0

[font.bold]
family = "Iosevka"
style = "Bold"

[font.normal]
family = "Iosevka"
style = "Regular"

[scrolling]
history = 100

[window]
opacity = 0.75

[window.padding]
x = 15
y = 15
